---
title: "DisneyAnalysis"
author: "Willa Van Liew"
date: "2023-03-03"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(skimr)
library(survival)
library(survminer)
library(fitdistrplus)
ds = read_csv("./data/disney_plus_titles.csv")
```
```{r}
movies = ds %>%
  filter(type == "Movie")

movies = movies %>%
  mutate(duration = as.integer(str_replace(movies$duration, " min","" )))
```
```{r}
km = survfit(Surv(movies$duration)~movies$rating)

ggsurvplot(fit = km, 
           data = movies, 
           palette="lancet",
           risk.table = F,
           conf.int=F,
           legend = "bottom", 
           legend.title = "Rating",
           legend.labs = c("G", "PG","PG-13","TV-14","TV-G","TV-PG","TV-Y","TV-Y7","TV-Y7-FV"))+
  labs(title="Film Length Survival Curve by Rating",
       x="Film length (mins)") 

survdiff(Surv(movies$duration)~movies$rating)
```
```{r}
movies %>%
  group_by(rating)%>%
  summarize(Number_of_films=n())

movies = movies %>%
  mutate(comb_rating = case_when(
    rating %in% c("TV-Y", "TV-Y7", "TV-Y7-FV") ~ "TV-Y",
    rating %in% c("G", "TV-G") ~ "G",
    rating %in% c("PG", "TV-PG") ~ "PG",
    rating %in% c("PG-13", "TV-14") ~ "PG-13"
  ))

km2 = survfit(Surv(movies$duration)~strata(movies$comb_rating))

survdiff(Surv(movies$duration)~movies$comb_rating)


ggsurvplot(fit=km2, 
           data=movies,            
           palette="lancet",
           risk.table = F,
           conf.int=T,
           legend = "bottom", 
           legend.title = "Rating",
           legend.labs = c("G", "PG","PG-13","TV-Y")) +
  labs(title="Combined Ratings Film Length Survival Curve",
       x="Film length (mins)")
```
```{r}
#myMod=survreg(surv2~ds$grp+ds$gender+ds$ageGroup4,dist="weibull")


#summary(myMod)

#AIC(myMod)

weibullreg = survreg(Surv(movies$duration)~strata(movies$comb_rating),dist="weibull")
summary(weibullreg)


logreg = survreg(Surv(movies$duration)~strata(movies$comb_rating),dist="lognormal")
summary(logreg)

expreg = survreg(Surv(movies$duration)~movies$comb_rating,dist="exponential")
summary(expreg)

gausreg = survreg(Surv(movies$duration)~strata(movies$comb_rating),dist="gaussian")


AIC(weibullreg)
AIC(gausreg)
AIC(logreg)
AIC(expreg)


BIC(weibullreg)
BIC(gausreg)
BIC(logreg)
BIC(expreg)


#weibull was the best fit

```

```{r}
reg2 = survreg(Surv(movies$duration)~movies$comb_rating)
summary(reg2)
```
```{r}
weibullreg2 = survreg(Surv(movies$duration)~movies$comb_rating,dist="weibull")
summary(weibullreg2)

logreg2 = survreg(Surv(movies$duration)~movies$comb_rating,dist="lognormal")
summary(logreg2)

expreg2 = survreg(Surv(movies$duration)~movies$comb_rating,dist="exponential")
summary(expreg2)

gausreg2 = survreg(Surv(movies$duration)~movies$comb_rating,dist="gaussian")


AIC(weibullreg2)
AIC(logreg2)
AIC(expreg2)
AIC(gausreg2)

BIC(weibullreg2)
BIC(gausreg2)
BIC(logreg2)
BIC(expreg2)

#weibull was the best fit
```

```{r}
print(paste0("G:", 1/0.789))
print(paste0("PG:", 1/0.415))
print(paste0("PG-13:", 1/0.506))
print(paste0("TV-Y:", 1/1.348))
```
the $\beta$ for TV-Y is 0.742 <br / > 
the $\beta$ for G is 1.267 <br / >
the $\beta$ for PG is 2.41 <br / >
the $\beta$ for PG-13 is 1.98 

```{r}
reg2 = survreg(Surv(movies$duration)~movies$comb_rating)
summary(reg2)
```
```{r}
movies = movies %>%
  mutate(type2 = case_when(
    rating = str_detect(rating, "TV") ~ "Made for TV",
    TRUE ~ "Made for Theaters"
  ))

km3 = survfit(Surv(movies$duration)~strata(movies$type2))

survdiff(Surv(movies$duration)~movies$type2)

ggsurvplot(fit=km3, 
           data=movies,            
           palette="lancet",
           risk.table = F,
           conf.int=T,
           legend = "bottom", 
           legend.title = "Debut type",
           legend.labs = c("Made for TV", "Made for Theaters")) +
  labs(title="Film Length Survival Curve by Film Debut Type",
       x="Film length (mins)") 
```
```{r}
unique(movies$release_year)

movies = movies %>% mutate(bin_year = cut(release_year, breaks=c(1920,1950,1970, 1990, 2000, 2010, 2022)))

movies = movies %>%
  mutate(bin_year = case_when(
    bin_year == "(2.01e+03,2.02e+03]" ~ "2011 to 2022",
    bin_year == "(2e+03,2.01e+03]" ~ "2001 to 2010",
    bin_year == "(1.99e+03,2e+03]" ~ "1991 to 2000",
    bin_year == "(1.97e+03,1.99e+03]" ~ "1971 to 1990",
    bin_year == "(1.95e+03,1.97e+03]" ~ "1951 to 1970",
    bin_year == "(1.92e+03,1.95e+03]" ~ "1920 to 1950"
  ))

km4 = survfit(Surv(movies$duration)~movies$bin_year)

survdiff(Surv(movies$duration)~movies$type2)


ggsurvplot(fit=km4, data=movies,
        palette="lancet",
           risk.table = F,
           conf.int=F,
           legend = "bottom", 
           legend.title = "Release period",
           legend.labs = c("1920-1950", "1951-1970","1971-1990","1991-2000","2001-2010","2011-2022")) +
  labs(title="Film Length Survival Curve by Release Period",
       x="Film length (mins)")
```
```{r}
theaters = movies %>%
  filter(type2 == "Made for Theaters")
```
```{r}
weibullreg3 = survreg(Surv(theaters$duration)~ theaters$release_year + theaters$rating,dist="weibull")
summary(weibullreg3)

logreg3 = survreg(Surv(theaters$duration)~ theaters$release_year + theaters$rating,dist="lognormal")
summary(logreg3)

expreg3 = survreg(Surv(theaters$duration)~ theaters$release_year + theaters$rating,dist="exponential")

summary(expreg3)

gausreg3 = survreg(Surv(theaters$duration)~ theaters$release_year + theaters$rating,dist="gaussian")


AIC(weibullreg3)
AIC(gausreg3)
AIC(logreg3)
AIC(expreg3)


BIC(weibullreg3)
BIC(gausreg3)
BIC(logreg3)
BIC(expreg3)


#gaussian was the best fit
```

```{r}
reg5 = survfit(Surv(movies$duration)~movies$release_year)
summary(reg5)

```

As the release year increases the duration increases by 0.0056
```{r}
reg4 = survreg(Surv(movies$duration)~movies$release_year)
ggsurvplot(data = movies, fit = reg4)
```

```{r}
reg_rel_year = survreg(Surv(theaters$duration)~ theaters$release_year)
summary(reg_rel_year)

```
The duration of movies (meant for theatrical release)
